"""Generate 30 varied coding questions (10 Python, 10 TypeScript, 10 Java) and import via API.

Evaluation patterns per language:
  Python:     globals injected from input dict, player code sets `result`, print(result) is compared
  TypeScript: globals injected via Object.assign, player code sets `result`, console.log(result) is compared
  Java:       player writes `public static String solve(String input)` that parses JSON string and returns answer
"""
import requests

BASE = "http://127.0.0.1:5001"
TOKEN = requests.post(f"{BASE}/api/auth/token").json()["token"]
HEADERS = {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}

# ──────────────────────────────────────────────
# Python questions
# ──────────────────────────────────────────────
python_questions = [
    {
        "category": "Coding",
        "difficulty": "Easy",
        "code_programming_language": "python",
        "description": "Given 3 variables, write code so that `result` equals the sum of the 3 numbers. Input: - a: First number - b: Second number - c: Third number",
        "correct_answer": "result = a + b + c",
        "code_sample_input": "{'a': 13, 'b': 17, 'c': 10}",
        "code_sample_output": "40",
        "code_hidden_input": "{'a': 20, 'b': 30, 'c': 15}",
        "code_hidden_output": "65",
        "hint": "A one-liner with the right arithmetic operator should do it.",
    },
    {
        "category": "Coding",
        "difficulty": "Easy",
        "code_programming_language": "python",
        "description": "You have a list of numbers. Set `result` to the largest value in the list. Input: - nums: A list of numbers",
        "correct_answer": "result = max(nums)",
        "code_sample_input": "{'nums': [3, 7, 2, 9, 1]}",
        "code_sample_output": "9",
        "code_hidden_input": "{'nums': [100, 50, 200, 75]}",
        "code_hidden_output": "200",
        "hint": "Python has a built-in function that returns the maximum value.",
    },
    {
        "category": "Coding",
        "difficulty": "Easy",
        "code_programming_language": "python",
        "description": "Given sets s1 and s2, set `result` to the elements that are in s1 but NOT in s2. Input: - s1: First set - s2: Second set",
        "correct_answer": "result = s1 - s2",
        "code_sample_input": "{'s1': {5, 6, 7, 8, 9}, 's2': {8, 9}}",
        "code_sample_output": "{5, 6, 7}",
        "code_hidden_input": "{'s1': {40, 10, 20, 30}, 's2': {40, 50, 30}}",
        "code_hidden_output": "{10, 20}",
        "hint": "Python sets support the minus operator for set difference.",
    },
    {
        "category": "Coding",
        "difficulty": "Easy",
        "code_programming_language": "python",
        "description": "A temperature is given in Celsius. Convert it to Fahrenheit and store in `result`. Input: - c: Temperature in Celsius",
        "correct_answer": "result = c * 9 / 5 + 32",
        "code_sample_input": "{'c': 0}",
        "code_sample_output": "32.0",
        "code_hidden_input": "{'c': 100}",
        "code_hidden_output": "212.0",
        "hint": "The formula is F = C * 9/5 + 32.",
    },
    {
        "category": "Coding",
        "difficulty": "Moderate",
        "code_programming_language": "python",
        "description": "Given an array of tuples, sort them by the second value of each tuple and store in `result`. Input: - a1: An array of tuples",
        "correct_answer": "result = sorted(a1, key=lambda x: x[1])",
        "code_sample_input": "{'a1': [(5, 10), (2, 5), (9, 7)]}",
        "code_sample_output": "[(2, 5), (9, 7), (5, 10)]",
        "code_hidden_input": "{'a1': [(1, 2), (3, 3), (1, 1)]}",
        "code_hidden_output": "[(1, 1), (1, 2), (3, 3)]",
        "hint": "The sorted() function accepts a key parameter. Use a lambda to pick the second element.",
    },
    {
        "category": "Coding",
        "difficulty": "Moderate",
        "code_programming_language": "python",
        "description": "Parse an AWS CloudFront URL to extract its components. Set `result` to a dictionary with keys: distribution_id (the part after https:// and before .cloudfront.net), resource_path (everything after .cloudfront.net), and resource_type (the file extension without the dot). Input: - url: A CloudFront URL",
        "correct_answer": "parts = url.replace('https://', '').split('.cloudfront.net')\nresult = {'distribution_id': parts[0], 'resource_path': parts[1], 'resource_type': parts[1].rsplit('.', 1)[1]}",
        "code_sample_input": "{'url': 'https://d2cxyz987.cloudfront.net/index.html'}",
        "code_sample_output": "{'distribution_id': 'd2cxyz987', 'resource_path': '/index.html', 'resource_type': 'html'}",
        "code_hidden_input": "{'url': 'https://d111111abcdef8.cloudfront.net/images/product/main.jpg'}",
        "code_hidden_output": "{'distribution_id': 'd111111abcdef8', 'resource_path': '/images/product/main.jpg', 'resource_type': 'jpg'}",
        "hint": "Split the URL around .cloudfront.net and use string methods to extract the parts.",
    },
    {
        "category": "Coding",
        "difficulty": "Moderate",
        "code_programming_language": "python",
        "description": "You have a nested list (a list of lists). Flatten it into a single list and store in `result`. Input: - matrix: A list of lists",
        "correct_answer": "result = [item for row in matrix for item in row]",
        "code_sample_input": "{'matrix': [[1, 2], [3, 4], [5]]}",
        "code_sample_output": "[1, 2, 3, 4, 5]",
        "code_hidden_input": "{'matrix': [[10, 20], [30]]}",
        "code_hidden_output": "[10, 20, 30]",
        "hint": "A nested list comprehension can iterate over rows and then items within each row.",
    },
    {
        "category": "Coding",
        "difficulty": "Hard",
        "code_programming_language": "python",
        "description": "Find the two numbers in a list that add up to a target sum. Set `result` to a list containing their indices. Input: - nums: A list of integers - target: The target sum",
        "correct_answer": "seen = {}\nfor i, n in enumerate(nums):\n    if target - n in seen:\n        result = [seen[target - n], i]\n        break\n    seen[n] = i",
        "code_sample_input": "{'nums': [2, 7, 11, 15], 'target': 9}",
        "code_sample_output": "[0, 1]",
        "code_hidden_input": "{'nums': [3, 2, 4], 'target': 6}",
        "code_hidden_output": "[1, 2]",
        "hint": "Use a dictionary to store numbers you have already seen and their indices.",
    },
    {
        "category": "Coding",
        "difficulty": "Hard",
        "code_programming_language": "python",
        "description": "Check whether a string of brackets is properly balanced. Set `result` to True if every opening bracket has a matching closer in the right order, False otherwise. Bracket pairs: (), [], {}. Input: - s: A string of brackets",
        "correct_answer": "stack = []\npairs = {')': '(', ']': '[', '}': '{'}\nresult = True\nfor c in s:\n    if c in '([{':\n        stack.append(c)\n    elif c in pairs:\n        if not stack or stack[-1] != pairs[c]:\n            result = False\n            break\n        stack.pop()\nelse:\n    result = len(stack) == 0",
        "code_sample_input": "{'s': '({[]})'}",
        "code_sample_output": "True",
        "code_hidden_input": "{'s': '([)]'}",
        "code_hidden_output": "False",
        "hint": "Use a stack to track opening brackets and match them with closing ones.",
    },
    {
        "category": "Coding",
        "difficulty": "Hard",
        "code_programming_language": "python",
        "description": "Given two strings, find the length of their longest common subsequence (not substring — characters don't need to be adjacent). Set `result` to that length. Input: - s1: First string - s2: Second string",
        "correct_answer": "m, n = len(s1), len(s2)\ndp = [[0] * (n + 1) for _ in range(m + 1)]\nfor i in range(1, m + 1):\n    for j in range(1, n + 1):\n        if s1[i-1] == s2[j-1]:\n            dp[i][j] = dp[i-1][j-1] + 1\n        else:\n            dp[i][j] = max(dp[i-1][j], dp[i][j-1])\nresult = dp[m][n]",
        "code_sample_input": "{'s1': 'abcde', 's2': 'ace'}",
        "code_sample_output": "3",
        "code_hidden_input": "{'s1': 'abc', 's2': 'def'}",
        "code_hidden_output": "0",
        "hint": "Use dynamic programming with a 2D table. Compare characters and build up from subproblems.",
    },
]

# ──────────────────────────────────────────────
# TypeScript questions
# ──────────────────────────────────────────────
typescript_questions = [
    {
        "category": "Coding",
        "difficulty": "Easy",
        "code_programming_language": "typescript",
        "description": "You have a temperature in Celsius. Convert it to Fahrenheit and store in `result`. Input: - c: Temperature in Celsius",
        "correct_answer": "const result = c * 9 / 5 + 32;",
        "code_sample_input": '{"c": 0}',
        "code_sample_output": "32",
        "code_hidden_input": '{"c": 100}',
        "code_hidden_output": "212",
        "hint": "The formula is F = C * 9/5 + 32.",
    },
    {
        "category": "Coding",
        "difficulty": "Easy",
        "code_programming_language": "typescript",
        "description": "Count how many words are in a sentence. Words are separated by spaces. Store the count in `result`. Input: - s: A string",
        "correct_answer": 'const result = s.trim().split(/\\s+/).length;',
        "code_sample_input": '{"s": "hello world foo"}',
        "code_sample_output": "3",
        "code_hidden_input": '{"s": "one two three four five"}',
        "code_hidden_output": "5",
        "hint": "Split the string on whitespace and count the resulting array length.",
    },
    {
        "category": "Coding",
        "difficulty": "Easy",
        "code_programming_language": "typescript",
        "description": "Check whether an array contains a specific value. Set `result` to true or false. Input: - arr: An array - val: A value to search for",
        "correct_answer": "const result = arr.includes(val);",
        "code_sample_input": '{"arr": [1, 2, 3, 4, 5], "val": 3}',
        "code_sample_output": "true",
        "code_hidden_input": '{"arr": [10, 20, 30], "val": 15}',
        "code_hidden_output": "false",
        "hint": "Arrays have an includes() method that checks for membership.",
    },
    {
        "category": "Coding",
        "difficulty": "Easy",
        "code_programming_language": "typescript",
        "description": "Repeat a string a given number of times and store in `result`. Input: - s: A string - n: Number of repetitions",
        "correct_answer": "const result = s.repeat(n);",
        "code_sample_input": '{"s": "ab", "n": 3}',
        "code_sample_output": "ababab",
        "code_hidden_input": '{"s": "xyz", "n": 2}',
        "code_hidden_output": "xyzxyz",
        "hint": "Strings have a repeat() method.",
    },
    {
        "category": "Coding",
        "difficulty": "Moderate",
        "code_programming_language": "typescript",
        "description": "Implement FizzBuzz for a single number. Set `result` to 'FizzBuzz' if n is divisible by both 3 and 5, 'Fizz' if only by 3, 'Buzz' if only by 5, or the number as a string otherwise. Input: - n: A positive integer",
        "correct_answer": 'const result = n % 15 === 0 ? "FizzBuzz" : n % 3 === 0 ? "Fizz" : n % 5 === 0 ? "Buzz" : String(n);',
        "code_sample_input": '{"n": 15}',
        "code_sample_output": "FizzBuzz",
        "code_hidden_input": '{"n": 9}',
        "code_hidden_output": "Fizz",
        "hint": "Check divisibility by 15 first (both 3 and 5), then 3, then 5.",
    },
    {
        "category": "Coding",
        "difficulty": "Moderate",
        "code_programming_language": "typescript",
        "description": "Swap the keys and values of an object. Set `result` to the new object. Input: - obj: An object with string values",
        "correct_answer": "const result: Record<string, string> = {}; for (const [k, v] of Object.entries(obj)) result[v as string] = k;",
        "code_sample_input": '{"obj": {"a": "1", "b": "2", "c": "3"}}',
        "code_sample_output": '{"1": "a", "2": "b", "3": "c"}',
        "code_hidden_input": '{"obj": {"name": "alice", "role": "admin"}}',
        "code_hidden_output": '{"alice": "name", "admin": "role"}',
        "hint": "Use Object.entries() to iterate and build a new object with keys and values flipped.",
    },
    {
        "category": "Coding",
        "difficulty": "Moderate",
        "code_programming_language": "typescript",
        "description": "Convert a sentence to title case — capitalize the first letter of each word, lowercase the rest. Store in `result`. Input: - s: A string",
        "correct_answer": 'const result = s.split(" ").map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join(" ");',
        "code_sample_input": '{"s": "hello world"}',
        "code_sample_output": "Hello World",
        "code_hidden_input": '{"s": "the quick brown fox"}',
        "code_hidden_output": "The Quick Brown Fox",
        "hint": "Split on spaces, capitalize the first character of each word, then join back.",
    },
    {
        "category": "Coding",
        "difficulty": "Hard",
        "code_programming_language": "typescript",
        "description": "Find the elements that appear in both arrays (intersection), preserving the order from the first array. Store in `result`. Input: - a: First array - b: Second array",
        "correct_answer": "const setB = new Set(b); const result = a.filter((x: any) => setB.has(x));",
        "code_sample_input": '{"a": [1, 2, 3, 4, 5], "b": [2, 4, 6]}',
        "code_sample_output": "[2, 4]",
        "code_hidden_input": '{"a": [10, 20, 30], "b": [30, 40, 10]}',
        "code_hidden_output": "[10, 30]",
        "hint": "Put one array into a Set for O(1) lookups, then filter the other array.",
    },
    {
        "category": "Coding",
        "difficulty": "Hard",
        "code_programming_language": "typescript",
        "description": "Apply run-length encoding to a string. Replace consecutive identical characters with the character followed by its count. Store in `result`. For example 'aaabbc' becomes 'a3b2c1'. Input: - s: A string",
        "correct_answer": 'let result = ""; let i = 0; while (i < s.length) { let c = s[i]; let count = 0; while (i < s.length && s[i] === c) { count++; i++; } result += c + count; }',
        "code_sample_input": '{"s": "aaabbc"}',
        "code_sample_output": "a3b2c1",
        "code_hidden_input": '{"s": "wwwwaaadexxxxxx"}',
        "code_hidden_output": "w4a3d1e1x6",
        "hint": "Walk through the string, counting consecutive identical characters.",
    },
    {
        "category": "Coding",
        "difficulty": "Hard",
        "code_programming_language": "typescript",
        "description": "Transpose a matrix — rows become columns and columns become rows. Store the transposed matrix in `result`. Input: - matrix: A 2D array of numbers",
        "correct_answer": "const result = matrix[0].map((_: any, i: number) => matrix.map((row: any) => row[i]));",
        "code_sample_input": '{"matrix": [[1, 2, 3], [4, 5, 6]]}',
        "code_sample_output": "[[1, 4], [2, 5], [3, 6]]",
        "code_hidden_input": '{"matrix": [[1, 2], [3, 4], [5, 6]]}',
        "code_hidden_output": "[[1, 3, 5], [2, 4, 6]]",
        "hint": "Map over column indices, and for each column index, collect that element from every row.",
    },
]

# ──────────────────────────────────────────────
# Java questions
# All use: public static String solve(String input) { ... }
# Descriptions are varied — not all start the same way
# ──────────────────────────────────────────────
java_questions = [
    {
        "category": "Coding",
        "difficulty": "Easy",
        "code_programming_language": "java",
        "description": 'Two numbers x and y are provided as JSON. Write a solve() method that parses them and returns their product. Example input: {"x": 3, "y": 7} → "21"',
        "correct_answer": 'public static String solve(String input) {\n    String clean = input.replaceAll("[{}\"]", "");\n    String[] parts = clean.split(",");\n    int x = 0, y = 0;\n    for (String p : parts) {\n        String[] kv = p.split(":");\n        String key = kv[0].trim();\n        int val = Integer.parseInt(kv[1].trim());\n        if (key.equals("x")) x = val;\n        else if (key.equals("y")) y = val;\n    }\n    return String.valueOf(x * y);\n}',
        "code_sample_input": '{"x": 3, "y": 7}',
        "code_sample_output": "21",
        "code_hidden_input": '{"x": 12, "y": 5}',
        "code_hidden_output": "60",
        "hint": "Parse x and y from the JSON string, then multiply them.",
    },
    {
        "category": "Coding",
        "difficulty": "Easy",
        "code_programming_language": "java",
        "description": 'Given a number n as JSON, determine if it is positive, negative, or zero. Return the word as a string. Example: {"n": 5} → "positive"',
        "correct_answer": 'public static String solve(String input) {\n    String clean = input.replaceAll("[{}\"]", "");\n    int n = Integer.parseInt(clean.split(":")[1].trim());\n    return n > 0 ? "positive" : n < 0 ? "negative" : "zero";\n}',
        "code_sample_input": '{"n": 5}',
        "code_sample_output": "positive",
        "code_hidden_input": '{"n": -3}',
        "code_hidden_output": "negative",
        "hint": "Compare n with 0 using conditional operators.",
    },
    {
        "category": "Coding",
        "difficulty": "Easy",
        "code_programming_language": "java",
        "description": 'A string s is provided as JSON. Return it converted to UPPERCASE. Example: {"s": "hello"} → "HELLO"',
        "correct_answer": 'public static String solve(String input) {\n    String s = input.split(":")[1].trim().replaceAll("[}\"]", "").trim();\n    return s.toUpperCase();\n}',
        "code_sample_input": '{"s": "hello"}',
        "code_sample_output": "HELLO",
        "code_hidden_input": '{"s": "java world"}',
        "code_hidden_output": "JAVA WORLD",
        "hint": "Java strings have a toUpperCase() method.",
    },
    {
        "category": "Coding",
        "difficulty": "Easy",
        "code_programming_language": "java",
        "description": 'How long is a piece of string? Given a string s as JSON, return its character count. Example: {"s": "hello"} → "5"',
        "correct_answer": 'public static String solve(String input) {\n    String s = input.split(":")[1].trim().replaceAll("[}\"]", "").trim();\n    return String.valueOf(s.length());\n}',
        "code_sample_input": '{"s": "hello"}',
        "code_sample_output": "5",
        "code_hidden_input": '{"s": "java programming"}',
        "code_hidden_output": "16",
        "hint": "Extract the string value and use the length() method.",
    },
    {
        "category": "Coding",
        "difficulty": "Moderate",
        "code_programming_language": "java",
        "description": 'Count the vowels (a, e, i, o, u — case insensitive) in a string provided as JSON. Return the count. Example: {"s": "Hello World"} → "3"',
        "correct_answer": 'public static String solve(String input) {\n    String s = input.split(":")[1].trim().replaceAll("[}\"]", "").trim().toLowerCase();\n    int count = 0;\n    for (char c : s.toCharArray()) {\n        if ("aeiou".indexOf(c) >= 0) count++;\n    }\n    return String.valueOf(count);\n}',
        "code_sample_input": '{"s": "Hello World"}',
        "code_sample_output": "3",
        "code_hidden_input": '{"s": "aeiou"}',
        "code_hidden_output": "5",
        "hint": "Loop through each character and check if it is one of aeiou.",
    },
    {
        "category": "Coding",
        "difficulty": "Moderate",
        "code_programming_language": "java",
        "description": 'Reverse the order of words in a sentence. Given a string s as JSON, return the words in reverse order. Example: {"s": "hello world foo"} → "foo world hello"',
        "correct_answer": 'public static String solve(String input) {\n    String s = input.split(":")[1].trim().replaceAll("[}\"]", "").trim();\n    String[] words = s.split(" ");\n    StringBuilder sb = new StringBuilder();\n    for (int i = words.length - 1; i >= 0; i--) {\n        if (sb.length() > 0) sb.append(" ");\n        sb.append(words[i]);\n    }\n    return sb.toString();\n}',
        "code_sample_input": '{"s": "hello world foo"}',
        "code_sample_output": "foo world hello",
        "code_hidden_input": '{"s": "the quick brown fox"}',
        "code_hidden_output": "fox brown quick the",
        "hint": "Split the string into words, then iterate in reverse order.",
    },
    {
        "category": "Coding",
        "difficulty": "Moderate",
        "code_programming_language": "java",
        "description": 'Find the greatest common divisor (GCD) of two numbers. Input is JSON with x and y. Example: {"x": 12, "y": 8} → "4"',
        "correct_answer": 'public static String solve(String input) {\n    String clean = input.replaceAll("[{}\"]", "");\n    String[] parts = clean.split(",");\n    int x = 0, y = 0;\n    for (String p : parts) {\n        String[] kv = p.split(":");\n        String key = kv[0].trim();\n        int val = Integer.parseInt(kv[1].trim());\n        if (key.equals("x")) x = val;\n        else if (key.equals("y")) y = val;\n    }\n    while (y != 0) { int t = y; y = x % y; x = t; }\n    return String.valueOf(x);\n}',
        "code_sample_input": '{"x": 12, "y": 8}',
        "code_sample_output": "4",
        "code_hidden_input": '{"x": 35, "y": 14}',
        "code_hidden_output": "7",
        "hint": "Use the Euclidean algorithm: repeatedly replace the larger number with the remainder.",
    },
    {
        "category": "Coding",
        "difficulty": "Hard",
        "code_programming_language": "java",
        "description": 'Is it a palindrome? Given a string s as JSON, return "true" if it reads the same forwards and backwards (case-insensitive), "false" otherwise. Example: {"s": "Racecar"} → "true"',
        "correct_answer": 'public static String solve(String input) {\n    String s = input.split(":")[1].trim().replaceAll("[}\"]", "").trim().toLowerCase();\n    String rev = new StringBuilder(s).reverse().toString();\n    return String.valueOf(s.equals(rev));\n}',
        "code_sample_input": '{"s": "Racecar"}',
        "code_sample_output": "true",
        "code_hidden_input": '{"s": "hello"}',
        "code_hidden_output": "false",
        "hint": "Convert to lowercase, reverse it, and compare with the original.",
    },
    {
        "category": "Coding",
        "difficulty": "Hard",
        "code_programming_language": "java",
        "description": 'Sum all prime numbers below n. Input is JSON with a number n. Use the Sieve of Eratosthenes. Example: {"n": 10} → "17" (2+3+5+7)',
        "correct_answer": 'public static String solve(String input) {\n    String clean = input.replaceAll("[{}\"]", "");\n    int n = Integer.parseInt(clean.split(":")[1].trim());\n    boolean[] sieve = new boolean[n];\n    java.util.Arrays.fill(sieve, true);\n    if (n > 0) sieve[0] = false;\n    if (n > 1) sieve[1] = false;\n    for (int i = 2; i * i < n; i++) {\n        if (sieve[i]) for (int j = i * i; j < n; j += i) sieve[j] = false;\n    }\n    long sum = 0;\n    for (int i = 2; i < n; i++) if (sieve[i]) sum += i;\n    return String.valueOf(sum);\n}',
        "code_sample_input": '{"n": 10}',
        "code_sample_output": "17",
        "code_hidden_input": '{"n": 20}',
        "code_hidden_output": "77",
        "hint": "Use the Sieve of Eratosthenes to find all primes below n, then sum them.",
    },
    {
        "category": "Coding",
        "difficulty": "Hard",
        "code_programming_language": "java",
        "description": 'Compute the nth Fibonacci number (0-indexed: fib(0)=0, fib(1)=1, fib(2)=1...). Input is JSON with n. Example: {"n": 6} → "8"',
        "correct_answer": 'public static String solve(String input) {\n    String clean = input.replaceAll("[{}\"]", "");\n    int n = Integer.parseInt(clean.split(":")[1].trim());\n    if (n <= 0) return "0";\n    if (n == 1) return "1";\n    long a = 0, b = 1;\n    for (int i = 2; i <= n; i++) { long t = a + b; a = b; b = t; }\n    return String.valueOf(b);\n}',
        "code_sample_input": '{"n": 6}',
        "code_sample_output": "8",
        "code_hidden_input": '{"n": 10}',
        "code_hidden_output": "55",
        "hint": "Use two variables to track the previous two Fibonacci numbers and iterate.",
    },
]

# ──────────────────────────────────────────────
# Import all questions via the API
# ──────────────────────────────────────────────
all_questions = python_questions + typescript_questions + java_questions

print(f"Importing {len(all_questions)} coding questions ({len(python_questions)} Python, {len(typescript_questions)} TypeScript, {len(java_questions)} Java)...\n")

resp = requests.post(
    f"{BASE}/api/questions/import",
    headers=HEADERS,
    json={"questions": all_questions},
)

if resp.status_code == 201:
    data = resp.json()
    print(f"Successfully imported {data['imported']} questions.\n")
    for q in data["questions"]:
        lang = q.get("code_programming_language", "?")
        print(f"  Q{q['id']} [{lang:10s}] [{q['difficulty']:8s}] {q['description'][:70]}...")
else:
    print(f"Import failed ({resp.status_code}): {resp.text}")
